version: "3"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  mongodb-kafka-connector:
    image: 'mongodb-kafka-connector'
    build:
      context: .
      dockerfile: connector.Dockerfile
    volumes:
      - ./connector/connect-standalone.properties:/opt/bitnami/kafka/config/connect-standalone.properties
      - ./connector/mongo.properties:/opt/bitnami/kafka/config/mongo.properties
    depends_on:
      - zookeeper
      - kafka

  mongo-primary:
    image: 'bitnami/mongodb:4.4.15'
    environment:
      ALLOW_EMPTY_PASSWORD: "false"
      MONGODB_ADVERTISED_HOSTNAME: "mongo-primary"
      MONGODB_REPLICA_SET_MODE: "primary"
      MONGODB_DATABASE: "edu-sharing"
      MONGODB_USERNAME: "notification"
      MONGODB_PASSWORD: "notification"
      MONGODB_ROOT_USER: "root"
      MONGODB_ROOT_PASSWORD: "root"
      MONGODB_REPLICA_SET_KEY: "notification"
    expose:
      - "27017"
    ports:
      - "27017:27017"

  mongo-secondary:
    image: 'bitnami/mongodb:4.4.15'
    depends_on:
      - mongo-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME: "mongo-secondary"
      MONGODB_REPLICA_SET_MODE: "secondary"
      MONGODB_INITIAL_PRIMARY_HOST: "mongo-primary"
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: "27017"
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: "root"
      MONGODB_REPLICA_SET_KEY: "notification"
    expose:
      - "27017"

  mongo-arbiter:
    image: 'bitnami/mongodb:4.4.15'
    depends_on:
      - mongo-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME: "mongo-arbiter"
      MONGODB_REPLICA_SET_MODE: "arbiter"
      MONGODB_INITIAL_PRIMARY_HOST: "mongo-primary"
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: "27017"
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: "root"
      MONGODB_REPLICA_SET_KEY: "notification"
    expose:
      - "27017"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
