version: '3.7'

services:

  kafka:
    image: "enterprise/edu_sharing-enterprise-repository-plugin-kafka-deploy-docker-build-kafka:maven-feature-kafka-plugin-SNAPSHOT"
    expose:
      - '9092'
      - '9093'
      - '9094'
    volumes:
      - kafka-data-volume:/bitnami
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: "CLIENT://:9092,EXTERNAL://:9093, CONTROLLER://:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://kafka:9092,EXTERNAL://${KAFKA_HOST:-localhost}:${KAFKA_EXTERNAL_PORT:-9093}"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "CLIENT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@127.0.0.1:9094"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${KAFKA_EXTERNAL_PORT:-9093}:9093"

  notification-service-db:
    image: "enterprise/edu_sharing-enterprise-repository-plugin-kafka-deploy-docker-build-mongo:maven-feature-kafka-plugin-SNAPSHOT"
    environment:
      ALLOW_EMPTY_PASSWORD: "false"
      MONGODB_ADVERTISED_HOSTNAME: "kafka-mongo-db"
      MONGODB_REPLICA_SET_MODE: "primary"
      MONGODB_DATABASE: "${KAFKA_SERVICES_DATABASE_NAME:-notification}"
      MONGODB_USERNAME: "${KAFKA_SERVICES_DATABASE_USER:-notification}"
      MONGODB_PASSWORD: "${KAFKA_SERVICES_DATABASES_PASS:-notification}"
      MONGODB_ROOT_USER: "${KAFKA_SERVICES_DATABASES_ROOT_USER:-root}"
      MONGODB_ROOT_PASSWORD: "${KAFKA_SERVICES_DATABASES_ROOT_PASS:-root}"
      MONGODB_REPLICA_SET_KEY: "${KAFKA_SERVICES_DATABASES_REPLICATION_SET_KEY:-notification}"
    expose:
      - "27017"
    volumes:
      - "notification-service-db-volume-data:/bitnami/mongodb"

  notification-service:
    image: "enterprise/edu_sharing-enterprise-repository-plugin-kafka-deploy-docker-build-notification-service:maven-feature-kafka-plugin-SNAPSHOT"
    command:
      - -Xms${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMS:-512m}
      - -Xmx${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMX:-512m}
      - -Dcom.sun.management.jmxremote
      - -Dcom.sun.management.jmxremote.authenticate=false
      - -Dcom.sun.management.jmxremote.port=7199
      - -Dcom.sun.management.jmxremote.ssl=false
    environment:
      SERVER_PORT: "8080"
      MAIL_SETTINGS_FROM: "noreply@edu-sharing.com"
      KAFKA_TOPICS_NOTIFICATION: "notification"
      KAFKA_TOPICS_USERDATA: "userdata"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      SPRING_MAIL_HOST: "repository-mailcatcher"
      SPRING_MAIL_PORT: "1025"
      SPRING_MAIL_USERNAME: "user"
      SPRING_MAIL_PASSWORD: "password"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      SPRING_MAIL_SEND_ADDRESS: "${NOTIFICATION_SERVICES_MAIL_SEND_ADDRESS:-noreply@notification-service.org}"
      REPOSITORY_MONGO_CONNECTION_STRING: "mongodb://${NOTIFICATION_SERVICES_DATABASES_USER:-notification}:${NOTIFICATION_SERVICES_DATABASES_PASS:-notification}@notification-service-db:27017/${NOTIFICATION_SERVICES_DATABASES_NAME:-notification}"
    expose:
      - "8080"
    depends_on:
      - kafka
      - notification-service-db

volumes:
  kafka-data-volume:
  notification-service-db-volume-data:
